---
title: "individual_jian"
author: "Jian Kai Lee;jiankailee"
date: "4/28/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
library(ggmosaic)
```

```{r fig.width=14, fig.height=9}
# Factor and second factor causing the crash, what are the most common?
# The percentage of crash type  and report type of data 

crash <- readr::read_csv('crash2016.csv')
#crash


#temp<-crash%>%group_by(PRIM_CONTRIBUTORY_CAUSE)%>%summarise(count=n())
#temp

crash<-crash%>%filter(PRIM_CONTRIBUTORY_CAUSE!="UNABLE TO DETERMINE")
crash<-crash%>%filter(PRIM_CONTRIBUTORY_CAUSE!="NOT APPLICABLE")
unique(crash$PRIM_CONTRIBUTORY_CAUSE)
crash%>%group_by(PRIM_CONTRIBUTORY_CAUSE)%>%summarise(total=n())%>%arrange(desc(total))

crash%>%group_by(PRIM_CONTRIBUTORY_CAUSE)%>%summarise(total=n())%>%
  ggplot(aes(x=reorder(PRIM_CONTRIBUTORY_CAUSE,total), y=total))+geom_histogram(stat = "identity")+coord_flip()+theme(axis.text.y = element_text(size = 10))+xlab("Primary cause")+ylab("Number of Accidents")+ggtitle("Primary Cause of Accidents in 2016")+geom_text(aes(label=total),hjust=-0.01)
#crash%>%ggplot(aes(x=PRIM_CONTRIBUTORY_CAUSE))+geom_histogram(stat = "count")


#secondary cause histogram bar chart
crash<-crash%>%filter(SEC_CONTRIBUTORY_CAUSE!="UNABLE TO DETERMINE")
crash<-crash%>%filter(SEC_CONTRIBUTORY_CAUSE!="NOT APPLICABLE")
unique(crash$SEC_CONTRIBUTORY_CAUSE)
crash%>%group_by(SEC_CONTRIBUTORY_CAUSE)%>%summarise(total=n())%>%arrange(desc(total))
crash%>%group_by(SEC_CONTRIBUTORY_CAUSE)%>%summarise(total=n())%>%
  ggplot(aes(x=reorder(SEC_CONTRIBUTORY_CAUSE,total),y=total))+geom_histogram(stat = "identity")+coord_flip()+theme(axis.text.y = element_text(size = 10))+xlab("Secondary Causes")+ylab("Number of Accidents")+ggtitle("Secondary Causes of Accidents in 2016")+geom_text(aes(label=total),hjust=-0.01)

# total accident 
crash<-crash%>%filter(!is.na(INJURIES_TOTAL))
sum(crash$INJURIES_TOTAL)
crash%>%group_by(PRIM_CONTRIBUTORY_CAUSE)%>%summarise(total=sum(INJURIES_TOTAL))%>%arrange(desc(total))
crash%>%group_by(PRIM_CONTRIBUTORY_CAUSE)%>%summarise(total=sum(INJURIES_TOTAL))%>%ggplot(aes(x=reorder(PRIM_CONTRIBUTORY_CAUSE,total),y=total))+geom_bar(stat="identity")+coord_flip()+theme(axis.text.y = element_text(size = 10))+xlab("Primary Cause")+ylab("Number Injuries")+ggtitle("Total Injuries in Primary Causes 2016")+geom_text(aes(label=total),hjust=-0.05)
```

```{r fig.width=12, fig.height=9}
crash<-crash%>%filter(!is.na(INJURIES_FATAL))
#crash<-crash%>%filter(INJURIES_FATAL>0)
crash%>%group_by(PRIM_CONTRIBUTORY_CAUSE)%>%summarise(total=sum(INJURIES_FATAL))%>%arrange(desc(total))
crash%>%group_by(PRIM_CONTRIBUTORY_CAUSE)%>%summarise(total=sum(INJURIES_FATAL))%>%ggplot(aes(x=reorder(PRIM_CONTRIBUTORY_CAUSE,total),y=total))+geom_bar(stat="identity")+coord_flip()+theme(axis.text.y = element_text(size = 7))+xlab("Primary Cause")+ylab("Number of Injuries")+ggtitle("Total Fatal Injuries in Primary Causes 2016")
```

```{r}
temp<-crash%>%filter(PRIM_CONTRIBUTORY_CAUSE=="FOLLOWING TOO CLOSELY"|PRIM_CONTRIBUTORY_CAUSE=="FAILING TO YIELD RIGHT-OF-WAY"|PRIM_CONTRIBUTORY_CAUSE=="IMPROPER OVERTAKING/PASSING")
#temp
temp%>%group_by(PRIM_CONTRIBUTORY_CAUSE)%>%ggplot(aes(x=CRASH_HOUR,fill=PRIM_CONTRIBUTORY_CAUSE))+geom_line(stat="count",aes(color=PRIM_CONTRIBUTORY_CAUSE))+xlab("Hours")+ylab("Number of Accidents")+ggtitle("Top 3 Primary Causes of Accidents occured in Hours")+labs(color='Primary Causes')
#crash%>%ggplot(aes(x=CRASH_HOUR))+geom_line(stat="count")

#crash%>%group_by(CRASH_MONTH)%>%ggplot(aes(x=reorder(PRIM_CONTRIBUTORY_CAUSE,INJURIES_TOTAL),y=INJURIES_TOTAL))+geom_bar(stat="identity")+coord_flip()+theme(axis.text.y = element_text(size = 6))+xlab("primary cause")+ylab("Total Injuries")+ggtitle("Total Injuries in each primary cause 2016")


# 
#crash%>%ggplot(aes(x=PRIM_CONTRIBUTORY_CAUSE,fill=LIGHTING_CONDITION))+geom_bar(stat = "count",position = "fill")+coord_flip()+theme(axis.text.y = element_text(size = 6))+theme(legend.position = "top",legend.text = element_text(size = 6),legend.title = element_text(size = 6))+xlab("primary cause")+ylab("ratio of lighting condtion in cause")+ggtitle("The ratio of lighting condition in each primary causes")

#crash%>%ggplot()+geom_mosaic(aes(x=product(LIGHTING_CONDITION),fill=LIGHTING_CONDITION))
```
